name: Run test, lint, and build on PR

on: pull_request

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yml

  build:
    needs:
      - test-and-lint
    uses: ./.github/workflows/build.yml
